import { Task, User } from '@/types/task';

export const mockUsers: User[] = [
  { id: 1, username: 'johndoe', email: 'john@example.com', fullName: 'John Doe' },
  { id: 2, username: 'janedoe', email: 'jane@example.com', fullName: 'Jane Smith' },
  { id: 3, username: 'alexchen', email: 'alex@example.com', fullName: 'Alex Chen' },
  { id: 4, username: 'sarahk', email: 'sarah@example.com', fullName: 'Sarah Kim' },
];

export const mockTasks: Task[] = [
  {
    id: 1,
    title: 'Implement JWT Authentication',
    description: 'Set up JWT token-based authentication with Spring Security for the task management API.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assignedToId: 1,
    assignedToName: 'John Doe',
    createdById: 2,
    createdByName: 'Jane Smith',
    createdDate: '2026-02-01T09:00:00',
    updatedDate: '2026-02-05T14:30:00',
    dueDate: '2026-02-15',
  },
  {
    id: 2,
    title: 'Design Database Schema',
    description: 'Create MySQL database schema for users and tasks tables with proper relationships and indices.',
    status: 'COMPLETED',
    priority: 'CRITICAL',
    assignedToId: 3,
    assignedToName: 'Alex Chen',
    createdById: 1,
    createdByName: 'John Doe',
    createdDate: '2026-01-28T10:00:00',
    updatedDate: '2026-02-03T16:00:00',
    dueDate: '2026-02-05',
  },
  {
    id: 3,
    title: 'Create REST API Documentation',
    description: 'Document all API endpoints with request/response examples using Swagger/OpenAPI specification.',
    status: 'NEW',
    priority: 'MEDIUM',
    assignedToId: 2,
    assignedToName: 'Jane Smith',
    createdById: 1,
    createdByName: 'John Doe',
    createdDate: '2026-02-06T08:00:00',
    updatedDate: '2026-02-06T08:00:00',
    dueDate: '2026-02-20',
  },
  {
    id: 4,
    title: 'Set Up Docker Compose',
    description: 'Configure Docker Compose for MySQL and Spring Boot application deployment with health checks.',
    status: 'COMPLETED',
    priority: 'HIGH',
    assignedToId: 4,
    assignedToName: 'Sarah Kim',
    createdById: 3,
    createdByName: 'Alex Chen',
    createdDate: '2026-01-25T11:00:00',
    updatedDate: '2026-02-01T09:00:00',
    dueDate: '2026-02-01',
  },
  {
    id: 5,
    title: 'Implement Task CRUD Operations',
    description: 'Build create, read, update, and delete operations for tasks with proper validation and error handling.',
    status: 'IN_PROGRESS',
    priority: 'CRITICAL',
    assignedToId: 1,
    assignedToName: 'John Doe',
    createdById: 2,
    createdByName: 'Jane Smith',
    createdDate: '2026-02-03T13:00:00',
    updatedDate: '2026-02-07T10:00:00',
    dueDate: '2026-02-10',
  },
  {
    id: 6,
    title: 'Add Input Validation',
    description: 'Add request validation for all API endpoints using Spring Validation annotations and custom validators.',
    status: 'NEW',
    priority: 'MEDIUM',
    assignedToId: null,
    assignedToName: null,
    createdById: 1,
    createdByName: 'John Doe',
    createdDate: '2026-02-07T07:00:00',
    updatedDate: '2026-02-07T07:00:00',
    dueDate: '2026-02-25',
  },
  {
    id: 7,
    title: 'Performance Testing',
    description: 'Run load tests and optimize database queries for better performance under high traffic conditions.',
    status: 'NEW',
    priority: 'LOW',
    assignedToId: 3,
    assignedToName: 'Alex Chen',
    createdById: 4,
    createdByName: 'Sarah Kim',
    createdDate: '2026-02-06T15:00:00',
    updatedDate: '2026-02-06T15:00:00',
    dueDate: '2026-03-01',
  },
  {
    id: 8,
    title: 'Fix CORS Configuration',
    description: 'Update CORS settings to allow specific origins instead of wildcard for production security compliance.',
    status: 'CLOSED',
    priority: 'HIGH',
    assignedToId: 4,
    assignedToName: 'Sarah Kim',
    createdById: 2,
    createdByName: 'Jane Smith',
    createdDate: '2026-01-20T09:00:00',
    updatedDate: '2026-01-30T17:00:00',
    dueDate: '2026-01-30',
  },
  {
    id: 9,
    title: 'Implement Error Handling',
    description: 'Create global exception handler with proper error response format and HTTP status codes.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assignedToId: 2,
    assignedToName: 'Jane Smith',
    createdById: 3,
    createdByName: 'Alex Chen',
    createdDate: '2026-02-04T10:00:00',
    updatedDate: '2026-02-07T08:00:00',
    dueDate: '2026-02-12',
  },
  {
    id: 10,
    title: 'Deploy to Cloud Infrastructure',
    description: 'Set up CI/CD pipeline and deploy the application to AWS with auto-scaling and monitoring.',
    status: 'NEW',
    priority: 'LOW',
    assignedToId: null,
    assignedToName: null,
    createdById: 1,
    createdByName: 'John Doe',
    createdDate: '2026-02-07T12:00:00',
    updatedDate: '2026-02-07T12:00:00',
    dueDate: '2026-03-15',
  },
];
